### ISSUE TITLE
Error: no such table PeriodicValues

### ISSUE THREAD

**Issue by piperoc** [happybruce/opcua#1]
First of all thank you so much for this effort. 

I tried running the code, but as I request a hist_read from UAExpert (with times that I know I have in the DB) I get these:

```
...
 MonitoredItem 1 | Created the MonitoredItem (Sampling Interval: 250.00ms, Queue Size: 1)
firstIndex_sqliteHDB | Error | no such table: PeriodicValues
lastIndex_sqliteHDB | Error | no such table: PeriodicValues
...
```

I looked at the DB (which I manually prepopulated) and all seems ok.

I'm not sure why you have a "DROP TABLE" statement in the context creation (I actually commented it out).

I can run nicolasr75 windows code without issues. But your code is more useful to me (and it's more up to date with the open62541 API).

THanks for the help

**Comment by happybruce** [comment]
Yes, when running code it will clear DB, so you cannot get data if read directly, also report error.  My original thinking is clear DB, then user create some history data and store it, then read history data.. 
You can comment "DROP TABLE" out, and you can also change SQL according to your requirement.

**Comment by piperoc** [comment]
Thank you @happybruce .
Things got better.

I commented the "DROP TABLE" and I created a table using the SQL code you use (differnent schema than what nicolasr75 wrote). 

At the bottom of this you can find a small python script I use to populate the table with random doubles.

The code seems to run correctly (no more exceptions on the server side).

But on the client (UAExpert), when I request a read I get a message I have never seen. 

```
HistoryReadRawModified succeeded
HistoryReadRawModified succeeded
HistoryReadRawModified succeeded
HistoryReadRawModified succeeded
HistoryReadRawModified succeeded
HistoryReadDataResults of node 'NS1|String|myDoubleValue' contains 7197 values
The type of the history values of node 'NS1|String|myDoubleValue' can not be displayed
```


I will keep investigating and update this as I find answers. 
Thanks again. 

In the meanwhile, here's the python code that fills in some data (like 3 months in the past at 15 minutes interval) in case anyone needs it.

```python
import curses
import os
import sqlite3
import random
from datetime import datetime, timedelta
from tqdm import tqdm

try:
    db_file = 'database.sqlite'
    if os.path.exists(db_file):
        os.remove(db_file)
        print("Updating database...")

    sqliteConnection = sqlite3.connect(db_file)
    cursor = sqliteConnection.cursor()
    print("Successfully Connected to SQLite")

    sqlite_select_Query = "select sqlite_version();"
    cursor.execute(sqlite_select_Query)
    record = cursor.fetchall()
    print("SQLite Database Version is: ", record)

    table_create_query = "CREATE TABLE PeriodicValues(MeasuringPointID INT, Value DOUBLE, Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);"
    cursor.execute(table_create_query)


    i = 1
    now = datetime.now()

    total_minutes = 43800 
    pbar = tqdm(total=total_minutes)
    while i < total_minutes:
      x = random.uniform(1.1,100.5)
      dateincrement = now - timedelta(minutes=(i))
      insert_query = """INSERT INTO "main"."PeriodicValues" ("Timestamp", "MeasuringPointID", "Value") VALUES ('""" + dateincrement.strftime("%Y-%m-%d %H:%M:%S") + """', '1', '""" + str(x) + """');"""
      count = cursor.execute(insert_query)
      sqliteConnection.commit()
      i += 1+15
      pbar.update(15)

    cursor.close()
    pbar.close()

except sqlite3.Error as error:
    print("Error while connecting to sqlite", error)
finally:
    if sqliteConnection:
        sqliteConnection.close()
        print("The SQLite connection is closed")
```

**Comment by piperoc** [comment]
Got it working. 
The issue was on the client side I had to set the query time range to UTC. The error will be displayed when the request contains times that are not in the stored range.
I guess to enhance that I should look into implementing bounds.

All good at the end. Thank you again for the attention.
I think this issue can be closed as resolved.

**Comment by happybruce** [comment]
Good to hear that it works.
